In [1]:
import numpy as np

# Condiciones

In [2]:
arr = np.linspace(1,10,10, dtype = 'int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [3]:
#arroja una lista booleana de aquellos que satsfagan la condicion
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [4]:
#arroja aquellos elementos que satisfagan la condicion
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [5]:
#mas de una condicion
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [6]:
#modificar aquellos que satisfacen cierta condicon
arr[arr>5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

# Operaciones

In [9]:
#operaciones con listas de python
lista = [1,2]
lista

[1, 2]

In [10]:
lista*2  #aqui significa una concatenacion

[1, 2, 1, 2]

In [14]:
arr = np.arange(0,10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Operaciones con un escalar

In [15]:
print(arr + 10)
print(arr - 1)
print(arr * 3)
print(arr / 2)

[10 11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7  8]
[ 0  3  6  9 12 15 18 21 24 27]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


Operaciones con un array

In [16]:
print(arr + arr2)
print(arr - arr2)
print(arr * arr2)
print(arr / arr2) #aqui arroja un error por una division 0/0 en el primer indice

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/tmp/ipykernel_1490/3183633886.py:4: RuntimeWarning: invalid value encountered in divide
  print(arr / arr2)


In [18]:
#tambien aplica para arrays con ndim > 1
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
print(matriz + matriz)
print(matriz - matriz)
print(matriz * matriz)
print(matriz / matriz) #aqui arroja un error por una division 0/0 en el primer indice

[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[ 0  1  4  9 16]
 [25 36 49 64 81]]
[[nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


/tmp/ipykernel_1490/1000627057.py:4: RuntimeWarning: invalid value encountered in divide
  print(matriz / matriz) #aqui arroja un error por una division 0/0 en el primer indice


Producto punto

In [21]:
#con array de ndim = 1
np.dot(arr,arr2) 

285

Producto entre matrices

In [23]:
# con array de ndim = 2
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [26]:
np.dot(matriz,matriz2.T) 

array([[ 30,  80],
       [ 80, 255]])