# Numpy

- Es una paquetería muy veloz
- Optimiza el almacenamiento en memoria
- Maneja muchos tipos de datos (arrays y matrices)

# Pandas

- Hereda todas las bondades de Numpy en cuanto a velocidad
- Poco código para la manipulación de datos
- Podemos manejar multiples formatos de archivos (csv,json,xlss)

In [2]:
import numpy as np

### Array
- Representa datos de una manera estructurada e indexada
- Podemos acceder a sus elementos de forma sencilla

In [1]:
lista = [1,2,3,4,5]
lista

[1, 2, 3, 4, 5]

In [5]:
#arreglo de una dimension
arr = np.array(lista)
type(arr)

numpy.ndarray

In [6]:
#arreglo de dos dimensiones
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Indexación
Para elegir posiciones de un elemento

In [8]:
print(arr)
print(arr[0])

[1 2 3 4 5]
1


In [10]:
#podemos operar sobre elementos de un array
arr[0] + arr[4]

6

In [12]:
#para el caso de matrices
print(matriz[0]) #filas
print(matriz[0,2]) #fila,columna

[1 2 3]
3


### Slicing
Nos permite seleccionar multiples valores en un array

In [15]:
print(arr[0:3])
print(arr[1:4])
print(arr[:2])  #arranca desde el inicio
print(arr[2:]) #termina hasta el final

[1 2 3]
[2 3 4]
[1 2]
[3 4 5]


In [19]:
print(arr[::3])  #inicio:final:pasos donde te incluye el primero

[1 4]


In [20]:
arr[-3:]

array([3, 4, 5])

In [21]:
matriz[1:] #de la fila 1 hacia adelante

array([[4, 5, 6],
       [7, 8, 9]])

In [23]:
matriz[1:,0:2] #lo mismo que el anterior pero con las primeras dos col 

array([[4, 5],
       [7, 8]])