In [1]:
import numpy as np

# Tipos de datos

Podemos configurar que tipo de datos contendrá nuestra array

In [3]:
arr = np.array([1,2,3,4,5])
print(arr.dtype) 
print(arr)

int64
[1 2 3 4 5]


In [4]:
arr = np.array([1,2,3,4,5], dtype='float64')
print(arr.dtype) 
print(arr) #el dato de tipo decimal es ideal para trabajar con redes neuronales

float64
[1. 2. 3. 4. 5.]


In [5]:
arr = np.array([0,1,2,3,4]) #transformar numeros a booleanos
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [6]:
arr = np.array(['0','1','2','3','4']) #transformar texto a numero
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

# Dimensiones de los datos

- Escalares: dim = 0 Un solo dato o valor

- Vectores: dim = 1 Listas de Python

- Matrices: dim = 2 Hoja de cálculo

- Tensor: dim > 3 Series de tiempo, imágenes, videos.


In [7]:
#Escalar
scalar = np.array(42)
print(scalar.ndim)

0


In [8]:
#Vector
vector = np.array([1,2,3])
print(vector.ndim)

1


In [12]:
#Matriz
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
print(matriz.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [13]:
#Tensor
tensor = np.array([[[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]]
        ])
print(tensor)
print(tensor.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


Agregar o eliminar dimensiones

In [15]:
#obligamos a que el numero de dimensiones sea de 10
vector = np.array([1,2,3], ndmin=10)
print(vector)
print(vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [16]:
#podemos expandir por filas o columnas
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [17]:
#para eliminar hacemos lo siguiente
print(vector, vector.ndim)
vector_2 = np.squeeze(vector) #este comando lo reduce hasta una dimension util
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
