In [1]:
import numpy as np

# Creando arrays

In [2]:
#lista en python
print(list(range(0,10)))


#array en numpy
print(np.arange(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
#podemos agregar pasos en ambos

print(list(range(0,10,2)))

print(np.arange(0,10,2))

[0, 2, 4, 6, 8]
[0 2 4 6 8]


In [4]:
#array de puros ceros
print(np.zeros(3))

print(np.zeros((5,5)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
#array de puros unos
print(np.ones(5))

print(np.ones((3,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#array con linspace que incluye el final a tambien
np.linspace(0,5,10)  #inicio, final, cuantos valores quiero

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [7]:
#matriz identidad
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#valores aleatorios entre 0 y 1
print(np.random.rand())

#valores aleatorios entre 0 y 1 con 1 dim
print(np.random.rand(4))

#valores aleatorios entre 0 y 1 con 2 dim
print(np.random.rand(3,3))



0.6571278757680934
[0.95654967 0.43614542 0.94247357 0.08742854]
[[0.741876   0.52541924 0.20780016]
 [0.58067458 0.70235867 0.19235912]
 [0.32514367 0.90911314 0.21321473]]


In [9]:
#numeros aleatorios enteros entre el 1 y 15
print(np.random.randint(1,15))

#numeros aleatorios enteros en una matriz
print(np.random.randint(1,15, (5,5)))

10
[[11  5  1  6  4]
 [ 7 12  7  9 12]
 [ 6  5  6  3  2]
 [12  6 12  9  2]
 [14  2  5  2  5]]


# Shape y Reshape

Te indica la forma de un arreglo para saber que tipo de estructura estás manejadon, ya sea un vector con 5 entradas de la forma (1,2,3,4,5), matrices 2x2 o 3x4, etc.

In [12]:
arr = np.random.randint(1,10,(3,2))
arr

array([[1, 9],
       [9, 9],
       [8, 9]])

In [11]:
#indica la forma en (filas, columnas)
arr.shape

(3, 2)

In [18]:
#podemos reordenar la forma a un shape valido
print(arr.reshape(1,6))
print("")
print(arr.reshape(2,3))
print("")

#no modifica el arr original
print(arr)

[[1 9 9 9 8 9]]

[[1 9 9]
 [9 8 9]]

[[1 9]
 [9 9]
 [8 9]]


Podemos reordenar en diferentes formas:

In [19]:
#Reordenamos como lo hace el lenguaje C
np.reshape(arr,(2,3),'C')

array([[1, 9, 9],
       [9, 8, 9]])

In [20]:
#Reordenamos como lo hace el lenguaje Fortran
np.reshape(arr,(2,3),'F')

array([[1, 8, 9],
       [9, 9, 9]])

In [21]:
#Reordenamos como mejor este optimizado los datos en memoria de mi computadora
np.reshape(arr,(2,3),'A')

array([[1, 9, 9],
       [9, 8, 9]])