In [1]:
import numpy as np

In [5]:
#generamos una matriz de 2x5
arr = np.random.randint(1,20,10)
matriz = arr.reshape(2,5)
print(arr)
print("")
print(matriz)

[12  7  2  3  7  6  7  2  8 19]

[[12  7  2  3  7]
 [ 6  7  2  8 19]]


## max() y min()

In [6]:
#Maximo de un array
print(arr.max())
print(matriz.max())

19
19


In [7]:
#maximo por fila
print(matriz.max(1))
#maximo por columna
print(matriz.max(0))

[12 19]
[12  7  2  8 19]


In [10]:
#indice donde se encuentra el primer maximo
print(arr.argmax())
print(matriz.argmax())
print(matriz.argmax(1))
print(matriz.argmax(0))

9
9
[0 4]
[0 0 0 1 1]


In [12]:
#Mínimo de un array
print(arr.min())
print(matriz.min())
print(arr.argmin())

2
2
2


In [14]:
#distancia entre el maximo y minimo
print(arr.ptp())

matriz.ptp(0)

17


array([ 6,  0,  0,  5, 12])

In [19]:
#ordenar del menor al mayor
arr.sort()
arr

array([ 2,  2,  3,  6,  7,  7,  7,  8, 12, 19])

## Estadisticos (percentil, median, mean, mode, std,...)

In [17]:
np.percentile(arr,50) #percentil 50 o mediana

7.0

In [21]:
np.median(arr) # mediana

7.0

In [22]:
np.mean(arr) # promedio

7.3

In [25]:
np.std(arr) # desv estandar

4.859012245302536

In [26]:
np.var(arr) # varianza

23.61

## Concatenate

Unir dos arrays de la misma o distinta dimensionalidad

In [27]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [39]:
#arroja error ya que "a" es de ndim = 2, mientras que "b" es ndim=1
#np.concatenate((a,b), axis=0)

In [40]:
#acomodamos dimension
c = np.expand_dims(b,axis=0)
print(c)
np.concatenate((a,c), axis=0)

[[5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
#matriz transpuesta
c.T

array([[5],
       [6]])

In [43]:
#aqui tendremos un error de dimensionalidad
#np.concatenate((a,c), axis=1)  

#utilizamos la transpuesta
np.concatenate((a,c.T), axis=1)  

array([[1, 2, 5],
       [3, 4, 6]])

# Copy()
Nos permite realizar modificaciones sobre copias de un array sin afectar al array original

In [46]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
#Si creamos un array en base a otro
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [50]:
# Y modificamos el nuevo array
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [51]:
#afectamos el original
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [52]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [53]:
#modificamos la copia
arr_copy[:] = 1
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
#no modificamos el original ya que la copia ocupa otro espacio en memoria
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Podemos utilizar la funcion id() de python vanilla para  saber que espacio en memoria ocupa cada cosa

In [55]:
print(id(arr))
print(id(trozo_de_arr))
print(id(arr_copy))

140510529711216
140510529713328
140510529713520
