# Producto de matrices
Producto entre matriz con vector

In [2]:
import numpy as np

In [3]:
escalr = 5.6
vector = np.array([2,3])
matriz = np.array([[1,2], [3,4], [5,6]])

In [19]:
A = matriz * vector # broadcasting (3,2) * (2) = (3,2)
B = matriz.dot(vector) # producto interno (3,2) x (2,1) = (3,1)

print(A,B, sep = '\n\n')

[[ 2  6]
 [ 6 12]
 [10 18]]

[ 8 18 28]


In [8]:
# el producto interno tambien se puede escribir como sigue
np.dot(matriz, vector)

array([ 8, 18, 28])

In [10]:
#aqui surge error por que las dimensiones no permiten el producto
#np.dot(vector, matriz)

Producto entre matrices

In [11]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])

In [12]:
# 4 filas y 3 columnas
print(A.shape)

(4, 3)


In [14]:
# 3 filas y 2 columnas
print(B.shape)

(3, 2)


In [17]:
C = A.dot(B)  #(4,3) x (3,2) si se puede
C

array([[ 45,  56],
       [ 99, 125],
       [153, 194],
       [207, 263]])

In [16]:
# D = B.dot(A) $ (3,4) x (2,4) NO se puede

In [18]:
d = np.array([[1,2],[1,2]])
c = np.array([[0,1],[0,1]])
d.dot(c)

array([[0, 3],
       [0, 3]])

### Propiedades del producto entre matrices
Se puede dar cuando el numero de columnas de la primera coincide con el numero de renglones de la segunda:
$$ A_{i,j} \times B_{j,k} = C_{i,k} $$
Además, tiene las siguientes propiedades
- Asociativa: $A\times (B \times C) = (A\times B) \times C $
- Distributiva: $A\times (B + C) = A\times B + A\times C $
- No es conmutativa : $A\times B \neq B \times A$ 

In [21]:
A = np.array([[2,3],[5,7],[11,13]]) # (3,2)
B = np.array([[1,3],[2,1]]) # (2,2)
C = np.array([[3,1],[4,2]]) # (2,2)

In [24]:
# Asociativa
ABC = A.dot(B.dot(C))
AB_C =  (A.dot(B)).dot(C)

print(ABC, AB_C, sep="\n")

[[ 60  26]
 [145  63]
 [295 129]]
[[ 60  26]
 [145  63]
 [295 129]]


In [25]:
# Distirbutiva
D = A.dot(B + C)
E = (A.dot(B)) + (A.dot(C))

print(D,E,sep = '\n')

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [26]:
# Conmutativa
F = B.dot(C)  #(2,2) x (2,2)
G = C.dot(B)  #(2,2) x (2,2)

print(F,G,sep = '\n')

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]


# Transposición
- $(AB)^{t} =  B^tA^t$
- $(A^t)^t$

In [27]:
A = np.array([[2,3],[5,7],[11,13]]) # (3,2)
B = np.array([[1,3],[2,1]]) # (2,2)

In [30]:
# Primera propiedad
AB_t = A.dot(B).T
B_tA_t = B.T.dot(A.T)

print(AB_t, B_tA_t, sep= '\n')

[[ 8 19 37]
 [ 9 22 46]]
[[ 8 19 37]
 [ 9 22 46]]


In [31]:
# segunda propiedad
A_t_t = A.T.T
print(A, A_t_t, sep= '\n')

[[ 2  3]
 [ 5  7]
 [11 13]]
[[ 2  3]
 [ 5  7]
 [11 13]]


# Matriz identidad, inversa, singular

Matriz identidad: Es aquella cuya diagonal está llena de 1 y 0 fuera de ella. Se denota por I y satisface:
$$I \times A  = A $$

Es el neutro multiplicativo

In [32]:
identidad = np.eye(4)  #(4,4)
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
vector = np.array([[1],[2],[3],[4]]) #(1,4)
print(identidad.dot(vector))

[[1.]
 [2.]
 [3.]
 [4.]]


Matriz inversa: Es aquella tal que multiplicada por una matriz A, nos da la identidad. Se denota por $A^{-1}$  y es el inverso multiplicativo.

$A \times A^{-1} = A^{-1} \times A=I$

- Cuando una matriz NO tiene inversa, se le llama matriz signular.

- Solo las matrices cuadradas tienen inversa

In [39]:
C = np.array([[1,2],[3,4]])

In [40]:
inversa_C = np.linalg.inv(C)
inversa_C

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [41]:
print(C.dot(inversa_C))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [43]:
print(inversa_C.dot(C))

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
